version: '3.9'

services:
  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      - DB_URL
      - PG_USER
      - PG_PASSWORD
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: {}
