FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests

EXPOSE 8080
EXPOSE 5005

CMD ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "./target/hotel-subscription-backend-0.0.1-SNAPSHOT.jar"]
